// <auto-generated />
using System;
using LegalLib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LegalLib.Migrations
{
    [DbContext(typeof(LegalLibContext))]
    [Migration("20200215024207_LegalLib")]
    partial class LegalLib
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LegalLib.Models.TblCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryID");

                    b.ToTable("TblCategory");
                });

            modelBuilder.Entity("LegalLib.Models.TblComment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("TblLegalDocumentDocumentID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentID");

                    b.HasIndex("TblLegalDocumentDocumentID");

                    b.ToTable("TblComment");
                });

            modelBuilder.Entity("LegalLib.Models.TblCriteria", b =>
                {
                    b.Property<int>("CriteriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Criteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CriteriaID");

                    b.ToTable("TblCriteria");
                });

            modelBuilder.Entity("LegalLib.Models.TblDK", b =>
                {
                    b.Property<int>("DKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KlasifikasiID")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TblKlasifikasiKlasifikasiID")
                        .HasColumnType("int");

                    b.Property<int?>("TblLegalDocumentDocumentID")
                        .HasColumnType("int");

                    b.HasKey("DKID");

                    b.HasIndex("TblKlasifikasiKlasifikasiID");

                    b.HasIndex("TblLegalDocumentDocumentID");

                    b.ToTable("TblDK");
                });

            modelBuilder.Entity("LegalLib.Models.TblFileAttach", b =>
                {
                    b.Property<int>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<string>("Filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TblLegalDocumentDocumentID")
                        .HasColumnType("int");

                    b.HasKey("FileID");

                    b.HasIndex("TblLegalDocumentDocumentID");

                    b.ToTable("TblFileAttach");
                });

            modelBuilder.Entity("LegalLib.Models.TblKlasifikasi", b =>
                {
                    b.Property<int>("KlasifikasiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Klasifikasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("KlasifikasiID");

                    b.ToTable("TblKlasifikasi");
                });

            modelBuilder.Entity("LegalLib.Models.TblLegalDocument", b =>
                {
                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<string>("ApproveStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Authority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Chapter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriteriaID")
                        .HasColumnType("int");

                    b.Property<string>("EnvironmentRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LegalRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Methods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NamaDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeopleRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perihal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PermitDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Regulation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Requirement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RevDocument")
                        .HasColumnType("int");

                    b.Property<int>("Revisi")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TblCategoryCategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("TblCriteriaCriteriaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TglAkhir")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TglMulai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TglUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploaderEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploaderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploaderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentID");

                    b.HasIndex("TblCategoryCategoryID");

                    b.HasIndex("TblCriteriaCriteriaID");

                    b.ToTable("TblLegalDocument");
                });

            modelBuilder.Entity("LegalLib.Models.TblComment", b =>
                {
                    b.HasOne("LegalLib.Models.TblLegalDocument", "TblLegalDocument")
                        .WithMany("TblComments")
                        .HasForeignKey("TblLegalDocumentDocumentID");
                });

            modelBuilder.Entity("LegalLib.Models.TblDK", b =>
                {
                    b.HasOne("LegalLib.Models.TblKlasifikasi", "TblKlasifikasi")
                        .WithMany("TblDKs")
                        .HasForeignKey("TblKlasifikasiKlasifikasiID");

                    b.HasOne("LegalLib.Models.TblLegalDocument", "TblLegalDocument")
                        .WithMany("TblDKs")
                        .HasForeignKey("TblLegalDocumentDocumentID");
                });

            modelBuilder.Entity("LegalLib.Models.TblFileAttach", b =>
                {
                    b.HasOne("LegalLib.Models.TblLegalDocument", "TblLegalDocument")
                        .WithMany("TblFileAttaches")
                        .HasForeignKey("TblLegalDocumentDocumentID");
                });

            modelBuilder.Entity("LegalLib.Models.TblLegalDocument", b =>
                {
                    b.HasOne("LegalLib.Models.TblCategory", "TblCategory")
                        .WithMany("TblLegalDocuments")
                        .HasForeignKey("TblCategoryCategoryID");

                    b.HasOne("LegalLib.Models.TblCriteria", "TblCriteria")
                        .WithMany("TblLegalDocuments")
                        .HasForeignKey("TblCriteriaCriteriaID");
                });
#pragma warning restore 612, 618
        }
    }
}
